using System;
using System.ComponentModel;

namespace GE.MyLearning.BL
{
	/// <summary>
	///		The data structure representation of the 'CourseIdea' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ICourseIdea 
	{
		/// <summary>			
		/// CourseideaID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "CourseIdea"</remarks>
		System.Int64 CourseideaId { get; set; }
				
		
		
		/// <summary>
		/// CourseID : 
		/// </summary>
		System.String  CourseId  { get; set; }
		
		/// <summary>
		/// CourseUserID : 
		/// </summary>
		System.String  CourseUserId  { get; set; }
		
		/// <summary>
		/// CourseUserDate : 
		/// </summary>
		System.DateTime?  CourseUserDate  { get; set; }
		
		/// <summary>
		/// CourseKnowledge : 
		/// </summary>
		System.String  CourseKnowledge  { get; set; }
		
		/// <summary>
		/// Courseinstance : 
		/// </summary>
		System.String  Courseinstance  { get; set; }
		
		/// <summary>
		/// CourseUserIdea : 
		/// </summary>
		System.String  CourseUserIdea  { get; set; }
		
		/// <summary>
		/// CheckUserID : 
		/// </summary>
		System.String  CheckUserId  { get; set; }
		
		/// <summary>
		/// CheckUserDate : 
		/// </summary>
		System.DateTime?  CheckUserDate  { get; set; }
		
		/// <summary>
		/// CheckUserIdea : 
		/// </summary>
		System.String  CheckUserIdea  { get; set; }
		
		/// <summary>
		/// Status : 
		/// </summary>
		System.Int32?  Status  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


