using System;
using System.ComponentModel;

namespace GE.MyLearning.BL
{
	/// <summary>
	///		The data structure representation of the 'LoginLog' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ILoginLog 
	{
		/// <summary>			
		/// LoginLogID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "LoginLog"</remarks>
		System.Int64 LoginLogId { get; set; }
				
		
		
		/// <summary>
		/// LogBeginTime : 
		/// </summary>
		System.DateTime  LogBeginTime  { get; set; }
		
		/// <summary>
		/// LogEndTime : 
		/// </summary>
		System.DateTime?  LogEndTime  { get; set; }
		
		/// <summary>
		/// MachineIP : 
		/// </summary>
		System.String  MachineIp  { get; set; }
		
		/// <summary>
		/// UserID : 
		/// </summary>
		System.String  UserId  { get; set; }
		
		/// <summary>
		/// Demo : 
		/// </summary>
		System.String  Demo  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


