using System;
using System.ComponentModel;

namespace GE.MyLearning.BL
{
	/// <summary>
	///		The data structure representation of the 'VU_NEWPOST' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IVuNewpost 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "VU_NEWPOST"</remarks>
		System.Int32 Id { get; set; }
				
		
		
		/// <summary>
		/// OBJECT : 
		/// </summary>
		System.String  SafeNameObject  { get; set; }
		
		/// <summary>
		/// CONENT : 
		/// </summary>
		System.String  Conent  { get; set; }
		
		/// <summary>
		/// SPOKERMAN : 
		/// </summary>
		System.String  Spokerman  { get; set; }
		
		/// <summary>
		/// SSO : 
		/// </summary>
		System.String  Sso  { get; set; }
		
		/// <summary>
		/// POPULARITY : 
		/// </summary>
		System.Int32?  Popularity  { get; set; }
		
		/// <summary>
		/// REPLYNUM : 
		/// </summary>
		System.Int32?  Replynum  { get; set; }
		
		/// <summary>
		/// REPLYMAN : 
		/// </summary>
		System.String  Replyman  { get; set; }
		
		/// <summary>
		/// time : 
		/// </summary>
		System.DateTime?  Time  { get; set; }
		
		/// <summary>
		/// lasttime : 
		/// </summary>
		System.DateTime?  Lasttime  { get; set; }
		
		/// <summary>
		/// tupian : 
		/// </summary>
		System.String  Tupian  { get; set; }
		
		/// <summary>
		/// fujian : 
		/// </summary>
		System.String  Fujian  { get; set; }
		
		/// <summary>
		/// icon : 
		/// </summary>
		System.String  Icon  { get; set; }
		
		/// <summary>
		/// isgreat : 
		/// </summary>
		System.Int32?  Isgreat  { get; set; }
		
		/// <summary>
		/// updatetime : 
		/// </summary>
		System.DateTime?  Updatetime  { get; set; }
		
		/// <summary>
		/// catogary : 
		/// </summary>
		System.String  Catogary  { get; set; }
		
		/// <summary>
		/// istop : 
		/// </summary>
		System.Int32?  Istop  { get; set; }
		
		/// <summary>
		/// isxingming : 
		/// </summary>
		System.Int32?  Isxingming  { get; set; }
		
		/// <summary>
		/// iskm : 
		/// </summary>
		System.Int32?  Iskm  { get; set; }
		
		/// <summary>
		/// score : 
		/// </summary>
		System.Decimal?  Score  { get; set; }
		
		/// <summary>
		/// closed : 
		/// </summary>
		System.Int32?  Closed  { get; set; }
		
		/// <summary>
		/// isdescore : 
		/// </summary>
		System.Int32?  Isdescore  { get; set; }
		
		/// <summary>
		/// opentime : 
		/// </summary>
		System.DateTime?  Opentime  { get; set; }
		
		/// <summary>
		/// closedtime : 
		/// </summary>
		System.DateTime?  Closedtime  { get; set; }
		
		/// <summary>
		/// replytimes : 
		/// </summary>
		System.Int32?  Replytimes  { get; set; }
		
		/// <summary>
		/// owner : 
		/// </summary>
		System.String  Owner  { get; set; }
		
		/// <summary>
		/// modality : 
		/// </summary>
		System.String  Modality  { get; set; }
		
		/// <summary>
		/// groupid : 
		/// </summary>
		System.Int32?  Groupid  { get; set; }
		
		/// <summary>
		/// isopen : 
		/// </summary>
		System.Int32?  Isopen  { get; set; }
		
		/// <summary>
		/// issue : 
		/// </summary>
		System.Int32?  Issue  { get; set; }
		
		/// <summary>
		/// askkm : 
		/// </summary>
		System.Int32?  Askkm  { get; set; }
		
		/// <summary>
		/// expert : 
		/// </summary>
		System.String  Expert  { get; set; }
		
		/// <summary>
		/// classid : 
		/// </summary>
		System.String  Classid  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


