
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Menus.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;
using Microsoft.Practices.EnterpriseLibrary.Validation;

using GE.MyLearning.BL.Validation;
#endregion

namespace GE.MyLearning.BL
{
	///<summary>
	/// An object representation of the 'Menus' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class MenusBase : EntityBase, IMenus, IEntityId<MenusKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private MenusEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private MenusEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private MenusEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Menus> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event MenusEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event MenusEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="MenusBase"/> instance.
		///</summary>
		public MenusBase()
		{
			this.entityData = new MenusEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="MenusBase"/> instance.
		///</summary>
		///<param name="_menuId"></param>
		///<param name="_parentMenuId"></param>
		///<param name="_menuName"></param>
		///<param name="_showOrder"></param>
		///<param name="_permissionId"></param>
		///<param name="_pageUrl"></param>
		///<param name="_helpInfo"></param>
		///<param name="_status"></param>
		public MenusBase(System.String _menuId, System.String _parentMenuId, System.String _menuName, 
			System.Int32? _showOrder, System.String _permissionId, System.String _pageUrl, System.String _helpInfo, 
			System.Int32 _status)
		{
			this.entityData = new MenusEntityData();
			this.backupData = null;

			this.MenuId = _menuId;
			this.ParentMenuId = _parentMenuId;
			this.MenuName = _menuName;
			this.ShowOrder = _showOrder;
			this.PermissionId = _permissionId;
			this.PageUrl = _pageUrl;
			this.HelpInfo = _helpInfo;
			this.Status = _status;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Menus"/> instance.
		///</summary>
		///<param name="_menuId"></param>
		///<param name="_parentMenuId"></param>
		///<param name="_menuName"></param>
		///<param name="_showOrder"></param>
		///<param name="_permissionId"></param>
		///<param name="_pageUrl"></param>
		///<param name="_helpInfo"></param>
		///<param name="_status"></param>
		public static Menus CreateMenus(System.String _menuId, System.String _parentMenuId, System.String _menuName, 
			System.Int32? _showOrder, System.String _permissionId, System.String _pageUrl, System.String _helpInfo, 
			System.Int32 _status)
		{
			Menus newMenus = new Menus();
			newMenus.MenuId = _menuId;
			newMenus.ParentMenuId = _parentMenuId;
			newMenus.MenuName = _menuName;
			newMenus.ShowOrder = _showOrder;
			newMenus.PermissionId = _permissionId;
			newMenus.PageUrl = _pageUrl;
			newMenus.HelpInfo = _helpInfo;
			newMenus.Status = _status;
			return newMenus;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MenuId property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[NotNullValidator(MessageTemplate="Property does not allow null values.", Tag="MenuID")]
		[ValidatorComposition(CompositionType.And, Tag="MenuID")]

		[StringLengthValidator(40, MessageTemplate="Maximum length has been exceeded.", Tag="MenuID")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 40)]
		public virtual System.String MenuId
		{
			get
			{
				return this.entityData.MenuId; 
			}
			
			set
			{
				if (this.entityData.MenuId == value)
					return;
					
				OnColumnChanging(MenusColumn.MenuId, this.entityData.MenuId);
				this.entityData.MenuId = value;
				this.EntityId.MenuId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MenusColumn.MenuId, this.entityData.MenuId);
				OnPropertyChanged("MenuId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the MenuID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the MenuID property.</remarks>
		/// <value>This type is varchar</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalMenuId
		{
			get { return this.entityData.OriginalMenuId; }
			set { this.entityData.OriginalMenuId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the ParentMenuId property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>


		[NotNullValidator(Negated=true, Tag="ParentMenuID")]
		[ValidatorComposition(CompositionType.Or, Tag="ParentMenuID")]
		[StringLengthValidator(40, MessageTemplate="Maximum length has been exceeded.", Tag="ParentMenuID")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 40)]
		public virtual System.String ParentMenuId
		{
			get
			{
				return this.entityData.ParentMenuId; 
			}
			
			set
			{
				if (this.entityData.ParentMenuId == value)
					return;
					
				OnColumnChanging(MenusColumn.ParentMenuId, this.entityData.ParentMenuId);
				this.entityData.ParentMenuId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MenusColumn.ParentMenuId, this.entityData.ParentMenuId);
				OnPropertyChanged("ParentMenuId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MenuName property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>


		[NotNullValidator(Negated=true, Tag="MenuName")]
		[ValidatorComposition(CompositionType.Or, Tag="MenuName")]
		[StringLengthValidator(40, MessageTemplate="Maximum length has been exceeded.", Tag="MenuName")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 40)]
		public virtual System.String MenuName
		{
			get
			{
				return this.entityData.MenuName; 
			}
			
			set
			{
				if (this.entityData.MenuName == value)
					return;
					
				OnColumnChanging(MenusColumn.MenuName, this.entityData.MenuName);
				this.entityData.MenuName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MenusColumn.MenuName, this.entityData.MenuName);
				OnPropertyChanged("MenuName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ShowOrder property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsShowOrderNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? ShowOrder
		{
			get
			{
				return this.entityData.ShowOrder; 
			}
			
			set
			{
				if (this.entityData.ShowOrder == value)
					return;
					
				OnColumnChanging(MenusColumn.ShowOrder, this.entityData.ShowOrder);
				this.entityData.ShowOrder = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MenusColumn.ShowOrder, this.entityData.ShowOrder);
				OnPropertyChanged("ShowOrder");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PermissionId property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>


		[NotNullValidator(Negated=true, Tag="PermissionID")]
		[ValidatorComposition(CompositionType.Or, Tag="PermissionID")]
		[StringLengthValidator(40, MessageTemplate="Maximum length has been exceeded.", Tag="PermissionID")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 40)]
		public virtual System.String PermissionId
		{
			get
			{
				return this.entityData.PermissionId; 
			}
			
			set
			{
				if (this.entityData.PermissionId == value)
					return;
					
				OnColumnChanging(MenusColumn.PermissionId, this.entityData.PermissionId);
				this.entityData.PermissionId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MenusColumn.PermissionId, this.entityData.PermissionId);
				OnPropertyChanged("PermissionId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PageUrl property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>


		[NotNullValidator(Negated=true, Tag="PageUrl")]
		[ValidatorComposition(CompositionType.Or, Tag="PageUrl")]
		[StringLengthValidator(200, MessageTemplate="Maximum length has been exceeded.", Tag="PageUrl")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public virtual System.String PageUrl
		{
			get
			{
				return this.entityData.PageUrl; 
			}
			
			set
			{
				if (this.entityData.PageUrl == value)
					return;
					
				OnColumnChanging(MenusColumn.PageUrl, this.entityData.PageUrl);
				this.entityData.PageUrl = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MenusColumn.PageUrl, this.entityData.PageUrl);
				OnPropertyChanged("PageUrl");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the HelpInfo property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>


		[NotNullValidator(Negated=true, Tag="HelpInfo")]
		[ValidatorComposition(CompositionType.Or, Tag="HelpInfo")]
		[StringLengthValidator(1000, MessageTemplate="Maximum length has been exceeded.", Tag="HelpInfo")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 1000)]
		public virtual System.String HelpInfo
		{
			get
			{
				return this.entityData.HelpInfo; 
			}
			
			set
			{
				if (this.entityData.HelpInfo == value)
					return;
					
				OnColumnChanging(MenusColumn.HelpInfo, this.entityData.HelpInfo);
				this.entityData.HelpInfo = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MenusColumn.HelpInfo, this.entityData.HelpInfo);
				OnPropertyChanged("HelpInfo");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Status property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Status
		{
			get
			{
				return this.entityData.Status; 
			}
			
			set
			{
				if (this.entityData.Status == value)
					return;
					
				OnColumnChanging(MenusColumn.Status, this.entityData.Status);
				this.entityData.Status = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MenusColumn.Status, this.entityData.Status);
				OnPropertyChanged("Status");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Menus"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MenuID", "ParentMenuID", "MenuName", "ShowOrder", "PermissionID", "PageUrl", "HelpInfo", "Status"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as MenusEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Menus) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Menus>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Menus);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Menus Entity 
		///</summary>
		protected virtual Menus Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Menus copy = new Menus();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.MenuId = this.MenuId;
					copy.OriginalMenuId = this.OriginalMenuId;
				copy.ParentMenuId = this.ParentMenuId;
				copy.MenuName = this.MenuName;
				copy.ShowOrder = this.ShowOrder;
				copy.PermissionId = this.PermissionId;
				copy.PageUrl = this.PageUrl;
				copy.HelpInfo = this.HelpInfo;
				copy.Status = this.Status;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Menus Entity 
		///</summary>
		public virtual Menus Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Menus Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Menus DeepCopy()
		{
			return EntityHelper.Clone<Menus>(this as Menus);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as MenusEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new MenusEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as MenusEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(MenusColumn column)
		{
			switch(column)
			{
					case MenusColumn.MenuId:
					return entityData.MenuId != _originalData.MenuId;
					case MenusColumn.ParentMenuId:
					return entityData.ParentMenuId != _originalData.ParentMenuId;
					case MenusColumn.MenuName:
					return entityData.MenuName != _originalData.MenuName;
					case MenusColumn.ShowOrder:
					return entityData.ShowOrder != _originalData.ShowOrder;
					case MenusColumn.PermissionId:
					return entityData.PermissionId != _originalData.PermissionId;
					case MenusColumn.PageUrl:
					return entityData.PageUrl != _originalData.PageUrl;
					case MenusColumn.HelpInfo:
					return entityData.HelpInfo != _originalData.HelpInfo;
					case MenusColumn.Status:
					return entityData.Status != _originalData.Status;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< MenusColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MenuId != _originalData.MenuId;
			result = result || entityData.ParentMenuId != _originalData.ParentMenuId;
			result = result || entityData.MenuName != _originalData.MenuName;
			result = result || entityData.ShowOrder != _originalData.ShowOrder;
			result = result || entityData.PermissionId != _originalData.PermissionId;
			result = result || entityData.PageUrl != _originalData.PageUrl;
			result = result || entityData.HelpInfo != _originalData.HelpInfo;
			result = result || entityData.Status != _originalData.Status;
			return result;
		}	
		
		///<summary>
		///  Returns a Menus Entity with the original data.
		///</summary>
		public Menus GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateMenus(
				_originalData.MenuId,
				_originalData.ParentMenuId,
				_originalData.MenuName,
				_originalData.ShowOrder,
				_originalData.PermissionId,
				_originalData.PageUrl,
				_originalData.HelpInfo,
				_originalData.Status
				);
				
			return (Menus)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="MenusBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is MenusBase)
				return ValueEquals(this, (MenusBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="MenusBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MenuId.GetHashCode() ^ 
					((this.ParentMenuId == null) ? string.Empty : this.ParentMenuId.ToString()).GetHashCode() ^ 
					((this.MenuName == null) ? string.Empty : this.MenuName.ToString()).GetHashCode() ^ 
					((this.ShowOrder == null) ? string.Empty : this.ShowOrder.ToString()).GetHashCode() ^ 
					((this.PermissionId == null) ? string.Empty : this.PermissionId.ToString()).GetHashCode() ^ 
					((this.PageUrl == null) ? string.Empty : this.PageUrl.ToString()).GetHashCode() ^ 
					((this.HelpInfo == null) ? string.Empty : this.HelpInfo.ToString()).GetHashCode() ^ 
					this.Status.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="MenusBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(MenusBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="MenusBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="MenusBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="MenusBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(MenusBase Object1, MenusBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MenuId != Object2.MenuId)
				equal = false;
			if ( Object1.ParentMenuId != null && Object2.ParentMenuId != null )
			{
				if (Object1.ParentMenuId != Object2.ParentMenuId)
					equal = false;
			}
			else if (Object1.ParentMenuId == null ^ Object2.ParentMenuId == null )
			{
				equal = false;
			}
			if ( Object1.MenuName != null && Object2.MenuName != null )
			{
				if (Object1.MenuName != Object2.MenuName)
					equal = false;
			}
			else if (Object1.MenuName == null ^ Object2.MenuName == null )
			{
				equal = false;
			}
			if ( Object1.ShowOrder != null && Object2.ShowOrder != null )
			{
				if (Object1.ShowOrder != Object2.ShowOrder)
					equal = false;
			}
			else if (Object1.ShowOrder == null ^ Object2.ShowOrder == null )
			{
				equal = false;
			}
			if ( Object1.PermissionId != null && Object2.PermissionId != null )
			{
				if (Object1.PermissionId != Object2.PermissionId)
					equal = false;
			}
			else if (Object1.PermissionId == null ^ Object2.PermissionId == null )
			{
				equal = false;
			}
			if ( Object1.PageUrl != null && Object2.PageUrl != null )
			{
				if (Object1.PageUrl != Object2.PageUrl)
					equal = false;
			}
			else if (Object1.PageUrl == null ^ Object2.PageUrl == null )
			{
				equal = false;
			}
			if ( Object1.HelpInfo != null && Object2.HelpInfo != null )
			{
				if (Object1.HelpInfo != Object2.HelpInfo)
					equal = false;
			}
			else if (Object1.HelpInfo == null ^ Object2.HelpInfo == null )
			{
				equal = false;
			}
			if (Object1.Status != Object2.Status)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((MenusBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static MenusComparer GetComparer()
        {
            return new MenusComparer();
        }
        */

        // Comparer delegates back to Menus
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Menus rhs, MenusColumn which)
        {
            switch (which)
            {
            	
            	
            	case MenusColumn.MenuId:
            		return this.MenuId.CompareTo(rhs.MenuId);
            		
            		                 
            	
            	
            	case MenusColumn.ParentMenuId:
            		return this.ParentMenuId.CompareTo(rhs.ParentMenuId);
            		
            		                 
            	
            	
            	case MenusColumn.MenuName:
            		return this.MenuName.CompareTo(rhs.MenuName);
            		
            		                 
            	
            	
            	case MenusColumn.ShowOrder:
            		return this.ShowOrder.Value.CompareTo(rhs.ShowOrder.Value);
            		
            		                 
            	
            	
            	case MenusColumn.PermissionId:
            		return this.PermissionId.CompareTo(rhs.PermissionId);
            		
            		                 
            	
            	
            	case MenusColumn.PageUrl:
            		return this.PageUrl.CompareTo(rhs.PageUrl);
            		
            		                 
            	
            	
            	case MenusColumn.HelpInfo:
            		return this.HelpInfo.CompareTo(rhs.HelpInfo);
            		
            		                 
            	
            	
            	case MenusColumn.Status:
            		return this.Status.CompareTo(rhs.Status);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<MenusKey> Members
		
		// member variable for the EntityId property
		private MenusKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual MenusKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new MenusKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Menus")
					.Append("|").Append( this.MenuId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{9}{8}- MenuId: {0}{8}- ParentMenuId: {1}{8}- MenuName: {2}{8}- ShowOrder: {3}{8}- PermissionId: {4}{8}- PageUrl: {5}{8}- HelpInfo: {6}{8}- Status: {7}{8}{10}", 
				this.MenuId,
				(this.ParentMenuId == null) ? string.Empty : this.ParentMenuId.ToString(),
				(this.MenuName == null) ? string.Empty : this.MenuName.ToString(),
				(this.ShowOrder == null) ? string.Empty : this.ShowOrder.ToString(),
				(this.PermissionId == null) ? string.Empty : this.PermissionId.ToString(),
				(this.PageUrl == null) ? string.Empty : this.PageUrl.ToString(),
				(this.HelpInfo == null) ? string.Empty : this.HelpInfo.ToString(),
				this.Status,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Menus' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class MenusEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// MenuID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Menus"</remarks>
		public System.String MenuId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.String OriginalMenuId;
		
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// ParentMenuID : 
		/// </summary>
		public System.String		  ParentMenuId = null;
		
		/// <summary>
		/// MenuName : 
		/// </summary>
		public System.String		  MenuName = null;
		
		/// <summary>
		/// ShowOrder : 
		/// </summary>
		public System.Int32?		  ShowOrder = null;
		
		/// <summary>
		/// PermissionID : 
		/// </summary>
		public System.String		  PermissionId = null;
		
		/// <summary>
		/// PageUrl : 
		/// </summary>
		public System.String		  PageUrl = null;
		
		/// <summary>
		/// HelpInfo : 
		/// </summary>
		public System.String		  HelpInfo = null;
		
		/// <summary>
		/// Status : 
		/// </summary>
		public System.Int32		  Status = (int)0;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			MenusEntityData _tmp = new MenusEntityData();
						
			_tmp.MenuId = this.MenuId;
			_tmp.OriginalMenuId = this.OriginalMenuId;
			
			_tmp.ParentMenuId = this.ParentMenuId;
			_tmp.MenuName = this.MenuName;
			_tmp.ShowOrder = this.ShowOrder;
			_tmp.PermissionId = this.PermissionId;
			_tmp.PageUrl = this.PageUrl;
			_tmp.HelpInfo = this.HelpInfo;
			_tmp.Status = this.Status;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			MenusEntityData _tmp = new MenusEntityData();
						
			_tmp.MenuId = this.MenuId;
			_tmp.OriginalMenuId = this.OriginalMenuId;
			
			_tmp.ParentMenuId = this.ParentMenuId;
			_tmp.MenuName = this.MenuName;
			_tmp.ShowOrder = this.ShowOrder;
			_tmp.PermissionId = this.PermissionId;
			_tmp.PageUrl = this.PageUrl;
			_tmp.HelpInfo = this.HelpInfo;
			_tmp.Status = this.Status;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MenusColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(MenusColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MenusColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(MenusColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MenusColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(MenusColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				MenusEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new MenusEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MenusColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(MenusColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				MenusEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new MenusEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region MenusEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Menus"/> object.
	/// </remarks>
	public class MenusEventArgs : System.EventArgs
	{
		private MenusColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the MenusEventArgs class.
		///</summary>
		public MenusEventArgs(MenusColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the MenusEventArgs class.
		///</summary>
		public MenusEventArgs(MenusColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The MenusColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="MenusColumn" />
		public MenusColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Menus related events.
	///</summary>
	public delegate void MenusEventHandler(object sender, MenusEventArgs e);
	
	#region MenusComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class MenusComparer : System.Collections.Generic.IComparer<Menus>
	{
		MenusColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:MenusComparer"/> class.
        /// </summary>
		public MenusComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:MenusComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public MenusComparer(MenusColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Menus"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Menus"/> to compare.</param>
        /// <param name="b">The second <c>Menus</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Menus a, Menus b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Menus entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Menus a, Menus b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public MenusColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region MenusKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Menus"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class MenusKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the MenusKey class.
		/// </summary>
		public MenusKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the MenusKey class.
		/// </summary>
		public MenusKey(MenusBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MenuId = entity.MenuId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the MenusKey class.
		/// </summary>
		public MenusKey(System.String _menuId)
		{
			#region Init Properties

			this.MenuId = _menuId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private MenusBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public MenusBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MenuId property
		private System.String _menuId;
		
		/// <summary>
		/// Gets or sets the MenuId property.
		/// </summary>
		public System.String MenuId
		{
			get { return _menuId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MenuId = value;
				
				_menuId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MenuId = ( values["MenuId"] != null ) ? (System.String) EntityUtil.ChangeType(values["MenuId"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MenuId", MenuId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MenuId: {0}{1}",
								MenuId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region MenusColumn Enum
	
	/// <summary>
	/// Enumerate the Menus columns.
	/// </summary>
	[Serializable]
	public enum MenusColumn : int
	{
		/// <summary>
		/// MenuId : 
		/// </summary>
		[EnumTextValue("MenuID")]
		[ColumnEnum("MenuID", typeof(System.String), System.Data.DbType.AnsiString, true, false, false, 40)]
		MenuId = 1,
		/// <summary>
		/// ParentMenuId : 
		/// </summary>
		[EnumTextValue("ParentMenuID")]
		[ColumnEnum("ParentMenuID", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 40)]
		ParentMenuId = 2,
		/// <summary>
		/// MenuName : 
		/// </summary>
		[EnumTextValue("MenuName")]
		[ColumnEnum("MenuName", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 40)]
		MenuName = 3,
		/// <summary>
		/// ShowOrder : 
		/// </summary>
		[EnumTextValue("ShowOrder")]
		[ColumnEnum("ShowOrder", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		ShowOrder = 4,
		/// <summary>
		/// PermissionId : 
		/// </summary>
		[EnumTextValue("PermissionID")]
		[ColumnEnum("PermissionID", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 40)]
		PermissionId = 5,
		/// <summary>
		/// PageUrl : 
		/// </summary>
		[EnumTextValue("PageUrl")]
		[ColumnEnum("PageUrl", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 200)]
		PageUrl = 6,
		/// <summary>
		/// HelpInfo : 
		/// </summary>
		[EnumTextValue("HelpInfo")]
		[ColumnEnum("HelpInfo", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 1000)]
		HelpInfo = 7,
		/// <summary>
		/// Status : 
		/// </summary>
		[EnumTextValue("Status")]
		[ColumnEnum("Status", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Status = 8
	}//End enum

	#endregion MenusColumn Enum

} // end namespace
