
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file RolePermission.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;
using Microsoft.Practices.EnterpriseLibrary.Validation;

using GE.MyLearning.BL.Validation;
#endregion

namespace GE.MyLearning.BL
{
	///<summary>
	/// An object representation of the 'RolePermission' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class RolePermissionBase : EntityBase, IRolePermission, IEntityId<RolePermissionKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private RolePermissionEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private RolePermissionEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private RolePermissionEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<RolePermission> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event RolePermissionEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event RolePermissionEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="RolePermissionBase"/> instance.
		///</summary>
		public RolePermissionBase()
		{
			this.entityData = new RolePermissionEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="RolePermissionBase"/> instance.
		///</summary>
		///<param name="_permissionId"></param>
		///<param name="_roleId"></param>
		public RolePermissionBase(System.String _permissionId, System.String _roleId)
		{
			this.entityData = new RolePermissionEntityData();
			this.backupData = null;

			this.PermissionId = _permissionId;
			this.RoleId = _roleId;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="RolePermission"/> instance.
		///</summary>
		///<param name="_permissionId"></param>
		///<param name="_roleId"></param>
		public static RolePermission CreateRolePermission(System.String _permissionId, System.String _roleId)
		{
			RolePermission newRolePermission = new RolePermission();
			newRolePermission.PermissionId = _permissionId;
			newRolePermission.RoleId = _roleId;
			return newRolePermission;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the PermissionId property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[NotNullValidator(MessageTemplate="Property does not allow null values.", Tag="PermissionID")]
		[ValidatorComposition(CompositionType.And, Tag="PermissionID")]

		[StringLengthValidator(40, MessageTemplate="Maximum length has been exceeded.", Tag="PermissionID")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 40)]
		public virtual System.String PermissionId
		{
			get
			{
				return this.entityData.PermissionId; 
			}
			
			set
			{
				if (this.entityData.PermissionId == value)
					return;
					
				OnColumnChanging(RolePermissionColumn.PermissionId, this.entityData.PermissionId);
				this.entityData.PermissionId = value;
				this.EntityId.PermissionId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RolePermissionColumn.PermissionId, this.entityData.PermissionId);
				OnPropertyChanged("PermissionId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the PermissionID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the PermissionID property.</remarks>
		/// <value>This type is varchar</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalPermissionId
		{
			get { return this.entityData.OriginalPermissionId; }
			set { this.entityData.OriginalPermissionId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the RoleId property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[NotNullValidator(MessageTemplate="Property does not allow null values.", Tag="RoleID")]
		[ValidatorComposition(CompositionType.And, Tag="RoleID")]

		[StringLengthValidator(20, MessageTemplate="Maximum length has been exceeded.", Tag="RoleID")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 20)]
		public virtual System.String RoleId
		{
			get
			{
				return this.entityData.RoleId; 
			}
			
			set
			{
				if (this.entityData.RoleId == value)
					return;
					
				OnColumnChanging(RolePermissionColumn.RoleId, this.entityData.RoleId);
				this.entityData.RoleId = value;
				this.EntityId.RoleId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RolePermissionColumn.RoleId, this.entityData.RoleId);
				OnPropertyChanged("RoleId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the RoleID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the RoleID property.</remarks>
		/// <value>This type is varchar</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalRoleId
		{
			get { return this.entityData.OriginalRoleId; }
			set { this.entityData.OriginalRoleId = value; }
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "RolePermission"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"PermissionID", "RoleID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as RolePermissionEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (RolePermission) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<RolePermission>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as RolePermission);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed RolePermission Entity 
		///</summary>
		protected virtual RolePermission Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			RolePermission copy = new RolePermission();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.PermissionId = this.PermissionId;
					copy.OriginalPermissionId = this.OriginalPermissionId;
				copy.RoleId = this.RoleId;
					copy.OriginalRoleId = this.OriginalRoleId;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed RolePermission Entity 
		///</summary>
		public virtual RolePermission Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed RolePermission Entity which is a deep copy of the current entity.
		///</summary>
		public virtual RolePermission DeepCopy()
		{
			return EntityHelper.Clone<RolePermission>(this as RolePermission);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as RolePermissionEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new RolePermissionEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as RolePermissionEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(RolePermissionColumn column)
		{
			switch(column)
			{
					case RolePermissionColumn.PermissionId:
					return entityData.PermissionId != _originalData.PermissionId;
					case RolePermissionColumn.RoleId:
					return entityData.RoleId != _originalData.RoleId;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< RolePermissionColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.PermissionId != _originalData.PermissionId;
			result = result || entityData.RoleId != _originalData.RoleId;
			return result;
		}	
		
		///<summary>
		///  Returns a RolePermission Entity with the original data.
		///</summary>
		public RolePermission GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateRolePermission(
				_originalData.PermissionId,
				_originalData.RoleId
				);
				
			return (RolePermission)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="RolePermissionBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is RolePermissionBase)
				return ValueEquals(this, (RolePermissionBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="RolePermissionBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.PermissionId.GetHashCode() ^ 
					this.RoleId.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="RolePermissionBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(RolePermissionBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="RolePermissionBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="RolePermissionBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="RolePermissionBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(RolePermissionBase Object1, RolePermissionBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.PermissionId != Object2.PermissionId)
				equal = false;
			if (Object1.RoleId != Object2.RoleId)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((RolePermissionBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static RolePermissionComparer GetComparer()
        {
            return new RolePermissionComparer();
        }
        */

        // Comparer delegates back to RolePermission
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(RolePermission rhs, RolePermissionColumn which)
        {
            switch (which)
            {
            	
            	
            	case RolePermissionColumn.PermissionId:
            		return this.PermissionId.CompareTo(rhs.PermissionId);
            		
            		                 
            	
            	
            	case RolePermissionColumn.RoleId:
            		return this.RoleId.CompareTo(rhs.RoleId);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<RolePermissionKey> Members
		
		// member variable for the EntityId property
		private RolePermissionKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual RolePermissionKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new RolePermissionKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("RolePermission")
					.Append("|").Append( this.PermissionId.ToString())
					.Append("|").Append( this.RoleId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{3}{2}- PermissionId: {0}{2}- RoleId: {1}{2}{4}", 
				this.PermissionId,
				this.RoleId,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'RolePermission' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class RolePermissionEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// PermissionID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "RolePermission"</remarks>
		public System.String PermissionId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.String OriginalPermissionId;
		
		/// <summary>			
		/// RoleID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "RolePermission"</remarks>
		public System.String RoleId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.String OriginalRoleId;
		
		#endregion
		
		#region Non Primary key(s)
		
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			RolePermissionEntityData _tmp = new RolePermissionEntityData();
						
			_tmp.PermissionId = this.PermissionId;
			_tmp.OriginalPermissionId = this.OriginalPermissionId;
			_tmp.RoleId = this.RoleId;
			_tmp.OriginalRoleId = this.OriginalRoleId;
			
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			RolePermissionEntityData _tmp = new RolePermissionEntityData();
						
			_tmp.PermissionId = this.PermissionId;
			_tmp.OriginalPermissionId = this.OriginalPermissionId;
			_tmp.RoleId = this.RoleId;
			_tmp.OriginalRoleId = this.OriginalRoleId;
			
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RolePermissionColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(RolePermissionColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RolePermissionColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(RolePermissionColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RolePermissionColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(RolePermissionColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				RolePermissionEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new RolePermissionEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RolePermissionColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(RolePermissionColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				RolePermissionEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new RolePermissionEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region RolePermissionEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="RolePermission"/> object.
	/// </remarks>
	public class RolePermissionEventArgs : System.EventArgs
	{
		private RolePermissionColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the RolePermissionEventArgs class.
		///</summary>
		public RolePermissionEventArgs(RolePermissionColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the RolePermissionEventArgs class.
		///</summary>
		public RolePermissionEventArgs(RolePermissionColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The RolePermissionColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="RolePermissionColumn" />
		public RolePermissionColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all RolePermission related events.
	///</summary>
	public delegate void RolePermissionEventHandler(object sender, RolePermissionEventArgs e);
	
	#region RolePermissionComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class RolePermissionComparer : System.Collections.Generic.IComparer<RolePermission>
	{
		RolePermissionColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:RolePermissionComparer"/> class.
        /// </summary>
		public RolePermissionComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:RolePermissionComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public RolePermissionComparer(RolePermissionColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="RolePermission"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="RolePermission"/> to compare.</param>
        /// <param name="b">The second <c>RolePermission</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(RolePermission a, RolePermission b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(RolePermission entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(RolePermission a, RolePermission b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public RolePermissionColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region RolePermissionKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="RolePermission"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class RolePermissionKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the RolePermissionKey class.
		/// </summary>
		public RolePermissionKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the RolePermissionKey class.
		/// </summary>
		public RolePermissionKey(RolePermissionBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.PermissionId = entity.PermissionId;
				this.RoleId = entity.RoleId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the RolePermissionKey class.
		/// </summary>
		public RolePermissionKey(System.String _permissionId, System.String _roleId)
		{
			#region Init Properties

			this.PermissionId = _permissionId;
			this.RoleId = _roleId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private RolePermissionBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public RolePermissionBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the PermissionId property
		private System.String _permissionId;
		
		/// <summary>
		/// Gets or sets the PermissionId property.
		/// </summary>
		public System.String PermissionId
		{
			get { return _permissionId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.PermissionId = value;
				
				_permissionId = value;
			}
		}
		
		// member variable for the RoleId property
		private System.String _roleId;
		
		/// <summary>
		/// Gets or sets the RoleId property.
		/// </summary>
		public System.String RoleId
		{
			get { return _roleId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.RoleId = value;
				
				_roleId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				PermissionId = ( values["PermissionId"] != null ) ? (System.String) EntityUtil.ChangeType(values["PermissionId"], typeof(System.String)) : string.Empty;
				RoleId = ( values["RoleId"] != null ) ? (System.String) EntityUtil.ChangeType(values["RoleId"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("PermissionId", PermissionId);
			values.Add("RoleId", RoleId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("PermissionId: {0}{2}RoleId: {1}{2}",
								PermissionId,
								RoleId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region RolePermissionColumn Enum
	
	/// <summary>
	/// Enumerate the RolePermission columns.
	/// </summary>
	[Serializable]
	public enum RolePermissionColumn : int
	{
		/// <summary>
		/// PermissionId : 
		/// </summary>
		[EnumTextValue("PermissionID")]
		[ColumnEnum("PermissionID", typeof(System.String), System.Data.DbType.AnsiString, true, false, false, 40)]
		PermissionId = 1,
		/// <summary>
		/// RoleId : 
		/// </summary>
		[EnumTextValue("RoleID")]
		[ColumnEnum("RoleID", typeof(System.String), System.Data.DbType.AnsiString, true, false, false, 20)]
		RoleId = 2
	}//End enum

	#endregion RolePermissionColumn Enum

} // end namespace
