
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Students.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;
using Microsoft.Practices.EnterpriseLibrary.Validation;

using GE.MyLearning.BL.Validation;
#endregion

namespace GE.MyLearning.BL
{
	///<summary>
	/// An object representation of the 'Students' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class StudentsBase : EntityBase, IStudents, IEntityId<StudentsKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private StudentsEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private StudentsEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private StudentsEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Students> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event StudentsEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event StudentsEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="StudentsBase"/> instance.
		///</summary>
		public StudentsBase()
		{
			this.entityData = new StudentsEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="StudentsBase"/> instance.
		///</summary>
		///<param name="_userId"></param>
		///<param name="_createTime"></param>
		///<param name="_status"></param>
		///<param name="_degreeId"></param>
		///<param name="_notes"></param>
		///<param name="_studies"></param>
		///<param name="_applyDate"></param>
		///<param name="_approvalofHuman"></param>
		///<param name="_approveofDate"></param>
		public StudentsBase(System.String _userId, System.DateTime? _createTime, System.Int32 _status, 
			System.Int32 _degreeId, System.String _notes, System.Int32 _studies, System.DateTime? _applyDate, 
			System.String _approvalofHuman, System.DateTime? _approveofDate)
		{
			this.entityData = new StudentsEntityData();
			this.backupData = null;

			this.UserId = _userId;
			this.CreateTime = _createTime;
			this.Status = _status;
			this.DegreeId = _degreeId;
			this.Notes = _notes;
			this.Studies = _studies;
			this.ApplyDate = _applyDate;
			this.ApprovalofHuman = _approvalofHuman;
			this.ApproveofDate = _approveofDate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Students"/> instance.
		///</summary>
		///<param name="_userId"></param>
		///<param name="_createTime"></param>
		///<param name="_status"></param>
		///<param name="_degreeId"></param>
		///<param name="_notes"></param>
		///<param name="_studies"></param>
		///<param name="_applyDate"></param>
		///<param name="_approvalofHuman"></param>
		///<param name="_approveofDate"></param>
		public static Students CreateStudents(System.String _userId, System.DateTime? _createTime, System.Int32 _status, 
			System.Int32 _degreeId, System.String _notes, System.Int32 _studies, System.DateTime? _applyDate, 
			System.String _approvalofHuman, System.DateTime? _approveofDate)
		{
			Students newStudents = new Students();
			newStudents.UserId = _userId;
			newStudents.CreateTime = _createTime;
			newStudents.Status = _status;
			newStudents.DegreeId = _degreeId;
			newStudents.Notes = _notes;
			newStudents.Studies = _studies;
			newStudents.ApplyDate = _applyDate;
			newStudents.ApprovalofHuman = _approvalofHuman;
			newStudents.ApproveofDate = _approveofDate;
			return newStudents;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the StudentId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 StudentId
		{
			get
			{
				return this.entityData.StudentId; 
			}
			
			set
			{
				if (this.entityData.StudentId == value)
					return;
					
				OnColumnChanging(StudentsColumn.StudentId, this.entityData.StudentId);
				this.entityData.StudentId = value;
				this.EntityId.StudentId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StudentsColumn.StudentId, this.entityData.StudentId);
				OnPropertyChanged("StudentId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the UserId property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[NotNullValidator(MessageTemplate="Property does not allow null values.", Tag="UserID")]
		[ValidatorComposition(CompositionType.And, Tag="UserID")]

		[StringLengthValidator(20, MessageTemplate="Maximum length has been exceeded.", Tag="UserID")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 20)]
		public virtual System.String UserId
		{
			get
			{
				return this.entityData.UserId; 
			}
			
			set
			{
				if (this.entityData.UserId == value)
					return;
					
				OnColumnChanging(StudentsColumn.UserId, this.entityData.UserId);
				this.entityData.UserId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StudentsColumn.UserId, this.entityData.UserId);
				OnPropertyChanged("UserId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreateTime property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsCreateTimeNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? CreateTime
		{
			get
			{
				return this.entityData.CreateTime; 
			}
			
			set
			{
				if (this.entityData.CreateTime == value)
					return;
					
				OnColumnChanging(StudentsColumn.CreateTime, this.entityData.CreateTime);
				this.entityData.CreateTime = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StudentsColumn.CreateTime, this.entityData.CreateTime);
				OnPropertyChanged("CreateTime");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Status property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Status
		{
			get
			{
				return this.entityData.Status; 
			}
			
			set
			{
				if (this.entityData.Status == value)
					return;
					
				OnColumnChanging(StudentsColumn.Status, this.entityData.Status);
				this.entityData.Status = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StudentsColumn.Status, this.entityData.Status);
				OnPropertyChanged("Status");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DegreeId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 DegreeId
		{
			get
			{
				return this.entityData.DegreeId; 
			}
			
			set
			{
				if (this.entityData.DegreeId == value)
					return;
					
				OnColumnChanging(StudentsColumn.DegreeId, this.entityData.DegreeId);
				this.entityData.DegreeId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StudentsColumn.DegreeId, this.entityData.DegreeId);
				OnPropertyChanged("DegreeId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Notes property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>


		[NotNullValidator(Negated=true, Tag="Notes")]
		[ValidatorComposition(CompositionType.Or, Tag="Notes")]
		[StringLengthValidator(500, MessageTemplate="Maximum length has been exceeded.", Tag="Notes")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 500)]
		public virtual System.String Notes
		{
			get
			{
				return this.entityData.Notes; 
			}
			
			set
			{
				if (this.entityData.Notes == value)
					return;
					
				OnColumnChanging(StudentsColumn.Notes, this.entityData.Notes);
				this.entityData.Notes = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StudentsColumn.Notes, this.entityData.Notes);
				OnPropertyChanged("Notes");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Studies property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Studies
		{
			get
			{
				return this.entityData.Studies; 
			}
			
			set
			{
				if (this.entityData.Studies == value)
					return;
					
				OnColumnChanging(StudentsColumn.Studies, this.entityData.Studies);
				this.entityData.Studies = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StudentsColumn.Studies, this.entityData.Studies);
				OnPropertyChanged("Studies");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ApplyDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsApplyDateNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? ApplyDate
		{
			get
			{
				return this.entityData.ApplyDate; 
			}
			
			set
			{
				if (this.entityData.ApplyDate == value)
					return;
					
				OnColumnChanging(StudentsColumn.ApplyDate, this.entityData.ApplyDate);
				this.entityData.ApplyDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StudentsColumn.ApplyDate, this.entityData.ApplyDate);
				OnPropertyChanged("ApplyDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ApprovalofHuman property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>


		[NotNullValidator(Negated=true, Tag="ApprovalofHuman")]
		[ValidatorComposition(CompositionType.Or, Tag="ApprovalofHuman")]
		[StringLengthValidator(20, MessageTemplate="Maximum length has been exceeded.", Tag="ApprovalofHuman")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String ApprovalofHuman
		{
			get
			{
				return this.entityData.ApprovalofHuman; 
			}
			
			set
			{
				if (this.entityData.ApprovalofHuman == value)
					return;
					
				OnColumnChanging(StudentsColumn.ApprovalofHuman, this.entityData.ApprovalofHuman);
				this.entityData.ApprovalofHuman = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StudentsColumn.ApprovalofHuman, this.entityData.ApprovalofHuman);
				OnPropertyChanged("ApprovalofHuman");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ApproveofDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsApproveofDateNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? ApproveofDate
		{
			get
			{
				return this.entityData.ApproveofDate; 
			}
			
			set
			{
				if (this.entityData.ApproveofDate == value)
					return;
					
				OnColumnChanging(StudentsColumn.ApproveofDate, this.entityData.ApproveofDate);
				this.entityData.ApproveofDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(StudentsColumn.ApproveofDate, this.entityData.ApproveofDate);
				OnPropertyChanged("ApproveofDate");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Students"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"StudentID", "UserID", "CreateTime", "Status", "DegreeID", "Notes", "studies", "ApplyDate", "ApprovalofHuman", "ApproveofDate"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as StudentsEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Students) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Students>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Students);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Students Entity 
		///</summary>
		protected virtual Students Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Students copy = new Students();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.StudentId = this.StudentId;
				copy.UserId = this.UserId;
				copy.CreateTime = this.CreateTime;
				copy.Status = this.Status;
				copy.DegreeId = this.DegreeId;
				copy.Notes = this.Notes;
				copy.Studies = this.Studies;
				copy.ApplyDate = this.ApplyDate;
				copy.ApprovalofHuman = this.ApprovalofHuman;
				copy.ApproveofDate = this.ApproveofDate;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Students Entity 
		///</summary>
		public virtual Students Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Students Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Students DeepCopy()
		{
			return EntityHelper.Clone<Students>(this as Students);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as StudentsEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new StudentsEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as StudentsEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(StudentsColumn column)
		{
			switch(column)
			{
					case StudentsColumn.StudentId:
					return entityData.StudentId != _originalData.StudentId;
					case StudentsColumn.UserId:
					return entityData.UserId != _originalData.UserId;
					case StudentsColumn.CreateTime:
					return entityData.CreateTime != _originalData.CreateTime;
					case StudentsColumn.Status:
					return entityData.Status != _originalData.Status;
					case StudentsColumn.DegreeId:
					return entityData.DegreeId != _originalData.DegreeId;
					case StudentsColumn.Notes:
					return entityData.Notes != _originalData.Notes;
					case StudentsColumn.Studies:
					return entityData.Studies != _originalData.Studies;
					case StudentsColumn.ApplyDate:
					return entityData.ApplyDate != _originalData.ApplyDate;
					case StudentsColumn.ApprovalofHuman:
					return entityData.ApprovalofHuman != _originalData.ApprovalofHuman;
					case StudentsColumn.ApproveofDate:
					return entityData.ApproveofDate != _originalData.ApproveofDate;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< StudentsColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.StudentId != _originalData.StudentId;
			result = result || entityData.UserId != _originalData.UserId;
			result = result || entityData.CreateTime != _originalData.CreateTime;
			result = result || entityData.Status != _originalData.Status;
			result = result || entityData.DegreeId != _originalData.DegreeId;
			result = result || entityData.Notes != _originalData.Notes;
			result = result || entityData.Studies != _originalData.Studies;
			result = result || entityData.ApplyDate != _originalData.ApplyDate;
			result = result || entityData.ApprovalofHuman != _originalData.ApprovalofHuman;
			result = result || entityData.ApproveofDate != _originalData.ApproveofDate;
			return result;
		}	
		
		///<summary>
		///  Returns a Students Entity with the original data.
		///</summary>
		public Students GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateStudents(
				_originalData.UserId,
				_originalData.CreateTime,
				_originalData.Status,
				_originalData.DegreeId,
				_originalData.Notes,
				_originalData.Studies,
				_originalData.ApplyDate,
				_originalData.ApprovalofHuman,
				_originalData.ApproveofDate
				);
				
			return (Students)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="StudentsBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is StudentsBase)
				return ValueEquals(this, (StudentsBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="StudentsBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.StudentId.GetHashCode() ^ 
					this.UserId.GetHashCode() ^ 
					((this.CreateTime == null) ? string.Empty : this.CreateTime.ToString()).GetHashCode() ^ 
					this.Status.GetHashCode() ^ 
					this.DegreeId.GetHashCode() ^ 
					((this.Notes == null) ? string.Empty : this.Notes.ToString()).GetHashCode() ^ 
					this.Studies.GetHashCode() ^ 
					((this.ApplyDate == null) ? string.Empty : this.ApplyDate.ToString()).GetHashCode() ^ 
					((this.ApprovalofHuman == null) ? string.Empty : this.ApprovalofHuman.ToString()).GetHashCode() ^ 
					((this.ApproveofDate == null) ? string.Empty : this.ApproveofDate.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="StudentsBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(StudentsBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="StudentsBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="StudentsBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="StudentsBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(StudentsBase Object1, StudentsBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.StudentId != Object2.StudentId)
				equal = false;
			if (Object1.UserId != Object2.UserId)
				equal = false;
			if ( Object1.CreateTime != null && Object2.CreateTime != null )
			{
				if (Object1.CreateTime != Object2.CreateTime)
					equal = false;
			}
			else if (Object1.CreateTime == null ^ Object2.CreateTime == null )
			{
				equal = false;
			}
			if (Object1.Status != Object2.Status)
				equal = false;
			if (Object1.DegreeId != Object2.DegreeId)
				equal = false;
			if ( Object1.Notes != null && Object2.Notes != null )
			{
				if (Object1.Notes != Object2.Notes)
					equal = false;
			}
			else if (Object1.Notes == null ^ Object2.Notes == null )
			{
				equal = false;
			}
			if (Object1.Studies != Object2.Studies)
				equal = false;
			if ( Object1.ApplyDate != null && Object2.ApplyDate != null )
			{
				if (Object1.ApplyDate != Object2.ApplyDate)
					equal = false;
			}
			else if (Object1.ApplyDate == null ^ Object2.ApplyDate == null )
			{
				equal = false;
			}
			if ( Object1.ApprovalofHuman != null && Object2.ApprovalofHuman != null )
			{
				if (Object1.ApprovalofHuman != Object2.ApprovalofHuman)
					equal = false;
			}
			else if (Object1.ApprovalofHuman == null ^ Object2.ApprovalofHuman == null )
			{
				equal = false;
			}
			if ( Object1.ApproveofDate != null && Object2.ApproveofDate != null )
			{
				if (Object1.ApproveofDate != Object2.ApproveofDate)
					equal = false;
			}
			else if (Object1.ApproveofDate == null ^ Object2.ApproveofDate == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((StudentsBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static StudentsComparer GetComparer()
        {
            return new StudentsComparer();
        }
        */

        // Comparer delegates back to Students
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Students rhs, StudentsColumn which)
        {
            switch (which)
            {
            	
            	
            	case StudentsColumn.StudentId:
            		return this.StudentId.CompareTo(rhs.StudentId);
            		
            		                 
            	
            	
            	case StudentsColumn.UserId:
            		return this.UserId.CompareTo(rhs.UserId);
            		
            		                 
            	
            	
            	case StudentsColumn.CreateTime:
            		return this.CreateTime.Value.CompareTo(rhs.CreateTime.Value);
            		
            		                 
            	
            	
            	case StudentsColumn.Status:
            		return this.Status.CompareTo(rhs.Status);
            		
            		                 
            	
            	
            	case StudentsColumn.DegreeId:
            		return this.DegreeId.CompareTo(rhs.DegreeId);
            		
            		                 
            	
            	
            	case StudentsColumn.Notes:
            		return this.Notes.CompareTo(rhs.Notes);
            		
            		                 
            	
            	
            	case StudentsColumn.Studies:
            		return this.Studies.CompareTo(rhs.Studies);
            		
            		                 
            	
            	
            	case StudentsColumn.ApplyDate:
            		return this.ApplyDate.Value.CompareTo(rhs.ApplyDate.Value);
            		
            		                 
            	
            	
            	case StudentsColumn.ApprovalofHuman:
            		return this.ApprovalofHuman.CompareTo(rhs.ApprovalofHuman);
            		
            		                 
            	
            	
            	case StudentsColumn.ApproveofDate:
            		return this.ApproveofDate.Value.CompareTo(rhs.ApproveofDate.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<StudentsKey> Members
		
		// member variable for the EntityId property
		private StudentsKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual StudentsKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new StudentsKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Students")
					.Append("|").Append( this.StudentId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{11}{10}- StudentId: {0}{10}- UserId: {1}{10}- CreateTime: {2}{10}- Status: {3}{10}- DegreeId: {4}{10}- Notes: {5}{10}- Studies: {6}{10}- ApplyDate: {7}{10}- ApprovalofHuman: {8}{10}- ApproveofDate: {9}{10}{12}", 
				this.StudentId,
				this.UserId,
				(this.CreateTime == null) ? string.Empty : this.CreateTime.ToString(),
				this.Status,
				this.DegreeId,
				(this.Notes == null) ? string.Empty : this.Notes.ToString(),
				this.Studies,
				(this.ApplyDate == null) ? string.Empty : this.ApplyDate.ToString(),
				(this.ApprovalofHuman == null) ? string.Empty : this.ApprovalofHuman.ToString(),
				(this.ApproveofDate == null) ? string.Empty : this.ApproveofDate.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Students' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class StudentsEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// StudentID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Students"</remarks>
		public System.Int32 StudentId;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// UserID : 
		/// </summary>
		public System.String		  UserId = string.Empty;
		
		/// <summary>
		/// CreateTime : 
		/// </summary>
		public System.DateTime?		  CreateTime = null;
		
		/// <summary>
		/// Status : 
		/// </summary>
		public System.Int32		  Status = (int)0;
		
		/// <summary>
		/// DegreeID : 
		/// </summary>
		public System.Int32		  DegreeId = (int)0;
		
		/// <summary>
		/// Notes : 
		/// </summary>
		public System.String		  Notes = null;
		
		/// <summary>
		/// studies : 
		/// </summary>
		public System.Int32		  Studies = (int)0;
		
		/// <summary>
		/// ApplyDate : 
		/// </summary>
		public System.DateTime?		  ApplyDate = null;
		
		/// <summary>
		/// ApprovalofHuman : 
		/// </summary>
		public System.String		  ApprovalofHuman = null;
		
		/// <summary>
		/// ApproveofDate : 
		/// </summary>
		public System.DateTime?		  ApproveofDate = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			StudentsEntityData _tmp = new StudentsEntityData();
						
			_tmp.StudentId = this.StudentId;
			
			_tmp.UserId = this.UserId;
			_tmp.CreateTime = this.CreateTime;
			_tmp.Status = this.Status;
			_tmp.DegreeId = this.DegreeId;
			_tmp.Notes = this.Notes;
			_tmp.Studies = this.Studies;
			_tmp.ApplyDate = this.ApplyDate;
			_tmp.ApprovalofHuman = this.ApprovalofHuman;
			_tmp.ApproveofDate = this.ApproveofDate;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			StudentsEntityData _tmp = new StudentsEntityData();
						
			_tmp.StudentId = this.StudentId;
			
			_tmp.UserId = this.UserId;
			_tmp.CreateTime = this.CreateTime;
			_tmp.Status = this.Status;
			_tmp.DegreeId = this.DegreeId;
			_tmp.Notes = this.Notes;
			_tmp.Studies = this.Studies;
			_tmp.ApplyDate = this.ApplyDate;
			_tmp.ApprovalofHuman = this.ApprovalofHuman;
			_tmp.ApproveofDate = this.ApproveofDate;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="StudentsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(StudentsColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="StudentsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(StudentsColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="StudentsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(StudentsColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				StudentsEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new StudentsEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="StudentsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(StudentsColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				StudentsEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new StudentsEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region StudentsEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Students"/> object.
	/// </remarks>
	public class StudentsEventArgs : System.EventArgs
	{
		private StudentsColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the StudentsEventArgs class.
		///</summary>
		public StudentsEventArgs(StudentsColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the StudentsEventArgs class.
		///</summary>
		public StudentsEventArgs(StudentsColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The StudentsColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="StudentsColumn" />
		public StudentsColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Students related events.
	///</summary>
	public delegate void StudentsEventHandler(object sender, StudentsEventArgs e);
	
	#region StudentsComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class StudentsComparer : System.Collections.Generic.IComparer<Students>
	{
		StudentsColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:StudentsComparer"/> class.
        /// </summary>
		public StudentsComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:StudentsComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public StudentsComparer(StudentsColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Students"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Students"/> to compare.</param>
        /// <param name="b">The second <c>Students</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Students a, Students b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Students entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Students a, Students b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public StudentsColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region StudentsKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Students"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class StudentsKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the StudentsKey class.
		/// </summary>
		public StudentsKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the StudentsKey class.
		/// </summary>
		public StudentsKey(StudentsBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.StudentId = entity.StudentId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the StudentsKey class.
		/// </summary>
		public StudentsKey(System.Int32 _studentId)
		{
			#region Init Properties

			this.StudentId = _studentId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private StudentsBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public StudentsBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the StudentId property
		private System.Int32 _studentId;
		
		/// <summary>
		/// Gets or sets the StudentId property.
		/// </summary>
		public System.Int32 StudentId
		{
			get { return _studentId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.StudentId = value;
				
				_studentId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				StudentId = ( values["StudentId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["StudentId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("StudentId", StudentId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("StudentId: {0}{1}",
								StudentId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region StudentsColumn Enum
	
	/// <summary>
	/// Enumerate the Students columns.
	/// </summary>
	[Serializable]
	public enum StudentsColumn : int
	{
		/// <summary>
		/// StudentId : 
		/// </summary>
		[EnumTextValue("StudentID")]
		[ColumnEnum("StudentID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		StudentId = 1,
		/// <summary>
		/// UserId : 
		/// </summary>
		[EnumTextValue("UserID")]
		[ColumnEnum("UserID", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		UserId = 2,
		/// <summary>
		/// CreateTime : 
		/// </summary>
		[EnumTextValue("CreateTime")]
		[ColumnEnum("CreateTime", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		CreateTime = 3,
		/// <summary>
		/// Status : 
		/// </summary>
		[EnumTextValue("Status")]
		[ColumnEnum("Status", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Status = 4,
		/// <summary>
		/// DegreeId : 
		/// </summary>
		[EnumTextValue("DegreeID")]
		[ColumnEnum("DegreeID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		DegreeId = 5,
		/// <summary>
		/// Notes : 
		/// </summary>
		[EnumTextValue("Notes")]
		[ColumnEnum("Notes", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 500)]
		Notes = 6,
		/// <summary>
		/// Studies : 
		/// </summary>
		[EnumTextValue("studies")]
		[ColumnEnum("studies", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Studies = 7,
		/// <summary>
		/// ApplyDate : 
		/// </summary>
		[EnumTextValue("ApplyDate")]
		[ColumnEnum("ApplyDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		ApplyDate = 8,
		/// <summary>
		/// ApprovalofHuman : 
		/// </summary>
		[EnumTextValue("ApprovalofHuman")]
		[ColumnEnum("ApprovalofHuman", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		ApprovalofHuman = 9,
		/// <summary>
		/// ApproveofDate : 
		/// </summary>
		[EnumTextValue("ApproveofDate")]
		[ColumnEnum("ApproveofDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		ApproveofDate = 10
	}//End enum

	#endregion StudentsColumn Enum

} // end namespace
